name: C/C++ CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Installing dependency
        run: |
          python -m pip install --upgrade pip
          pip install cmake_format conan

      - name: Running formatting
        run: make format

      - name: Checking formatting
        run: git diff --exit-code

      - name: configure
        run: cmake -Bbuild -DENABLE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug

      - name: build
        run: cmake --build build -j4